#!/usr/bin/env php
<?php

// set ttyUSB here
$tty = '/dev/ttyUSB0';

if (isset($argv[1]) && ($argv[1] == 'config')) {
    showConfig($tty);
} else {
    showValues($tty);
}


function showConfigValue($valueName) {
    echo 'graph_vlabel maniektemp_' . $valueName . "\n";
    echo 'maniektemp_' . $valueName . '.label maniektemp_' . $valueName . "\n";
    echo 'maniektemp_' . $valueName . ".graph_category sensors\n";
}

function showValue($valueName, $temperature) {
    echo 'maniektemp_' . $valueName . '.value ' . $temperature . "\n";
}

function showConfig($tty) {
    echo "graph_title ManiekTemperature\n";
    $temperatures = getTemperatures($tty);

    for ($index = 0; $index < count($temperatures); $index++) {
        showConfigValue($index);
    };
}

function showValues($tty) {
    $temperatures = getTemperatures($tty);

    for ($index = 0; $index < count($temperatures); $index++) {
        showValue($index, $temperatures[$index]);
    };
}

function getTemperatures($tty) {
    $fileHandle = fopen($tty, 'r');
    $temperaturesString = trim(fgets($fileHandle));
    fclose($fileHandle);
    $temperatures = array_filter(explode(';', $temperaturesString), 'is_numeric');
    // echo $temperaturesString;
    return $temperatures;
}
