#!/usr/bin/env php
<?php

// set ttyUSB here
$tty = '/dev/ttyUSB0';

if (isset($argv[1]) && ($argv[1] == 'config')) {
    showConfig($tty);
} else {
    showValues($tty);
}


function showConfigValue($sensorId) {
    echo 'graph_vlabel maniektemp_' . $sensorId . "\n";
    echo 'maniektemp_' . $sensorId . '.label maniektemp_' . $sensorId . "\n";
    echo 'maniektemp_' . $sensorId . ".graph_category sensors\n";
}

function showValue($sensorId, $temperature) {
    echo 'maniektemp_' . $sensorId . '.value ' . $temperature . "\n";
}

function showConfig($tty) {
    echo "graph_title ManiekTemperature\n";
    $temperatures = getTemperatures($tty);

    foreach ($temperatures as $sensorId => $temperature) {
        showConfigValue($sensorId);
    }
}

function showValues($tty) {
    $temperatures = getTemperatures($tty);

    foreach ($temperatures as $sensorId => $temperature) {
        showValue($sensorId, $temperature);
    }
}

function before($needle, $inthat) {
    return substr($inthat, 0, strpos($inthat, $needle));
};

function between($needle1, $needle2, $inthat) {
    return before($needle2, after($needle1, $inthat));
};

function after($needle, $inthat) {
    if (!is_bool(strpos($inthat, $needle)))
        return substr($inthat, strpos($inthat, $needle) + strlen($needle));
};

function getTemperatures($tty) {
    $fileHandle = fopen($tty, 'r');
    $temperaturesString = fgets($fileHandle);        // let's skip one line to be sure we get string from the beginning
    $temperaturesString = fgets($fileHandle);
    fclose($fileHandle);
    $temperaturePairs = explode(';', $temperaturesString);

    $temperatures = array();
    foreach ($temperaturePairs as $temperatureString) {
        $sensorId = between('_', '=', $temperatureString);
        $temperature = after('=', $temperatureString);
        $temperatures[$sensorId] = $temperature;
    }

    return $temperatures;
}
